/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_ROCSAR_V1_ROCSAR_V1_COMMON_PB_H_INCLUDED
#define PB_ROCSAR_V1_ROCSAR_V1_COMMON_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Every failure the OBC can report back to a caller.

 ERROR_NONE is 0 and the host keys its success/failure decision off
 `CommandResponse.success`, not off this enum. The enum is for the operator
 reading a log; the boolean is for the code making a decision. */
typedef enum _rocsar_v1_ErrorCode {
    rocsar_v1_ErrorCode_ERROR_NONE = 0,
    rocsar_v1_ErrorCode_ERROR_INVALID_COMMAND = 1,
    rocsar_v1_ErrorCode_ERROR_INVALID_PARAMETER = 2,
    rocsar_v1_ErrorCode_ERROR_INVALID_SERVO = 3,
    rocsar_v1_ErrorCode_ERROR_INVALID_HEATER = 4,
    rocsar_v1_ErrorCode_ERROR_NOT_CONNECTED = 5,
    rocsar_v1_ErrorCode_ERROR_UNSUPPORTED = 6,
    rocsar_v1_ErrorCode_ERROR_HARDWARE_FAULT = 7,
    rocsar_v1_ErrorCode_ERROR_INTERNAL = 8,
    /* Teaching a servo its centre is the one operation that writes to hardware we
 do not own, and it can half-fail: the EEPROM write lands but the servo does
 not report the position we asked for. That is a materially different fact
 from a dead servo on the bus -- ERROR_HARDWARE_FAULT covers "nothing
 answered", and no write was attempted -- because here the servo's internal
 zero may now hold a partial change and the operator has to know before
 flying. Re-running `zero` converges, so this is recoverable, not fatal.

 This takes the reservation off deliberately, which is what the reservation
 existed to require. The draft's 9 was ERROR_BUSY, a different fact that
 nothing ever produced, so a stale generated host would render the wrong
 *name* for this failure -- and no host acts on it: the decision keys off
 CommandResponse.success, not off this enum. */
    rocsar_v1_ErrorCode_ERROR_CALIBRATION_FAILED = 9
} rocsar_v1_ErrorCode;

/* Whether the three servo feedback fields above it are a measurement.

 Declared as an enum for the Ground Station, which wants to switch on it.
 Carried on the wire as int32 in AntennaTelemetry.feedback_state, and the
 difference is deliberate: an unknown value from a future firmware decodes to
 a plain integer on an old host instead of failing the whole frame. */
typedef enum _rocsar_v1_FeedbackState {
    /* The servo has never answered. Position/load/temp are a command echo and
 init-time constants; nothing has been measured and nothing can be. */
    rocsar_v1_FeedbackState_FEEDBACK_UNKNOWN = 0,
    /* The ST3215 answered this read. The numbers are real. */
    rocsar_v1_FeedbackState_FEEDBACK_MEASURED = 1,
    /* It answered, then stopped. The numbers are the last real reading, stale. */
    rocsar_v1_FeedbackState_FEEDBACK_HELD = 2
} rocsar_v1_FeedbackState;

/* Health of one hardware or software subsystem, for the telemetry frame. */
typedef enum _rocsar_v1_SubsystemState {
    rocsar_v1_SubsystemState_SUBSYSTEM_UNSPECIFIED = 0,
    rocsar_v1_SubsystemState_SUBSYSTEM_DISCONNECTED = 1,
    rocsar_v1_SubsystemState_SUBSYSTEM_READY = 2,
    rocsar_v1_SubsystemState_SUBSYSTEM_BUSY = 3,
    rocsar_v1_SubsystemState_SUBSYSTEM_ERROR = 4
} rocsar_v1_SubsystemState;

/* Struct definitions */
/* One antenna axis, as the flight controller sees it.

 Two design decisions here are load-bearing and were both learned on the bench,
 not in review. Neither may be "simplified" away.

 1. feedback_state and feedback_error are int32, not their enums. See
    FeedbackState above and the note in pico.proto.
 2. load and temperature_c are real register reads. They used to be constants
    written once at init, which made a dead servo indistinguishable from an
    idle one. A console showing zeros for a motor that has not moved is worse
    than a console showing nothing, because zeros look like data. */
typedef struct _rocsar_v1_AntennaTelemetry {
    uint32_t servo_id;
    bool manual_mode;
    /* Live feedback from the ST3215 status registers.

 `current_tick` is a MEASUREMENT of where the encoder is, not an echo of the
 last commanded tick. It used to be the echo, and the change is silent: both
 are a uint32 near 2048. A client that treats it as the command is wrong by
 exactly the tracking error, which is small when the axis is tracking and
 large when it is stalled -- which is precisely when nobody is looking.

 The three are read from register P6, not synthesised. See the note on
 feedback_state below for what happens when a servo does not answer. */
    uint32_t current_tick;
    float current_angle_deg;
    /* Real register reads, and they arrived here in the opposite order to the
 shipped firmware: temperature_c was 5 and load was 6 there, and they are
 swapped here. Both are int32 and both survive a round trip, so a stale
 header produces a servo reporting -100% load at 85 C rather than an error.
 See the porting note at the top of pico.proto. */
    int32_t load;
    int32_t temperature_c;
    /* Configuration state, echoed from the flight controller. */
    uint32_t center_tick;
    float mount_offset_deg;
    float dir_multiplier;
    /* 0 unknown, 1 measured, 2 held. See FeedbackState. */
    int32_t feedback_state;
    /* The ST3215's own status byte from the same read, 0 == ERROR_NONE.
 Independent of feedback_state: a servo can answer a perfectly well-formed
 frame while reporting overheat or an overloaded regulator. This byte used
 to be parsed by nothing and discarded, so a servo in trouble read clean. */
    int32_t feedback_error;
    /* Whether this servo's internal zero has been taught and verified.

 The servo holds its own centre now: `zero` writes a position offset into
 the ST3215's EEPROM so the encoder reports 2048 at the airframe boresight,
 and the firmware verifies both the register and the resulting position
 before saying so. This bit rides the wire because the servo cannot report
 it itself -- a servo taught while sitting at exactly 2048 has a stored
 offset of zero, which is indistinguishable from a servo never taught.

 False on a freshly flashed servo, which is the normal state of a new axis.
 The firmware still aims, using the 2048 default; this bit is what tells an
 operator the centre is assumed rather than measured. Absence is not zero:
 do not render an untaught axis as if it were centred. */
    bool center_zeroed;
} rocsar_v1_AntennaTelemetry;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _rocsar_v1_ErrorCode_MIN rocsar_v1_ErrorCode_ERROR_NONE
#define _rocsar_v1_ErrorCode_MAX rocsar_v1_ErrorCode_ERROR_CALIBRATION_FAILED
#define _rocsar_v1_ErrorCode_ARRAYSIZE ((rocsar_v1_ErrorCode)(rocsar_v1_ErrorCode_ERROR_CALIBRATION_FAILED+1))

#define _rocsar_v1_FeedbackState_MIN rocsar_v1_FeedbackState_FEEDBACK_UNKNOWN
#define _rocsar_v1_FeedbackState_MAX rocsar_v1_FeedbackState_FEEDBACK_HELD
#define _rocsar_v1_FeedbackState_ARRAYSIZE ((rocsar_v1_FeedbackState)(rocsar_v1_FeedbackState_FEEDBACK_HELD+1))

#define _rocsar_v1_SubsystemState_MIN rocsar_v1_SubsystemState_SUBSYSTEM_UNSPECIFIED
#define _rocsar_v1_SubsystemState_MAX rocsar_v1_SubsystemState_SUBSYSTEM_ERROR
#define _rocsar_v1_SubsystemState_ARRAYSIZE ((rocsar_v1_SubsystemState)(rocsar_v1_SubsystemState_SUBSYSTEM_ERROR+1))



/* Initializer values for message structs */
#define rocsar_v1_AntennaTelemetry_init_default  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rocsar_v1_AntennaTelemetry_init_zero     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define rocsar_v1_AntennaTelemetry_servo_id_tag  1
#define rocsar_v1_AntennaTelemetry_manual_mode_tag 2
#define rocsar_v1_AntennaTelemetry_current_tick_tag 3
#define rocsar_v1_AntennaTelemetry_current_angle_deg_tag 4
#define rocsar_v1_AntennaTelemetry_load_tag      5
#define rocsar_v1_AntennaTelemetry_temperature_c_tag 6
#define rocsar_v1_AntennaTelemetry_center_tick_tag 7
#define rocsar_v1_AntennaTelemetry_mount_offset_deg_tag 8
#define rocsar_v1_AntennaTelemetry_dir_multiplier_tag 9
#define rocsar_v1_AntennaTelemetry_feedback_state_tag 10
#define rocsar_v1_AntennaTelemetry_feedback_error_tag 11
#define rocsar_v1_AntennaTelemetry_center_zeroed_tag 12

/* Struct field encoding specification for nanopb */
#define rocsar_v1_AntennaTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1) \
X(a, STATIC,   SINGULAR, BOOL,     manual_mode,       2) \
X(a, STATIC,   SINGULAR, UINT32,   current_tick,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    current_angle_deg,   4) \
X(a, STATIC,   SINGULAR, INT32,    load,              5) \
X(a, STATIC,   SINGULAR, INT32,    temperature_c,     6) \
X(a, STATIC,   SINGULAR, UINT32,   center_tick,       7) \
X(a, STATIC,   SINGULAR, FLOAT,    mount_offset_deg,   8) \
X(a, STATIC,   SINGULAR, FLOAT,    dir_multiplier,    9) \
X(a, STATIC,   SINGULAR, INT32,    feedback_state,   10) \
X(a, STATIC,   SINGULAR, INT32,    feedback_error,   11) \
X(a, STATIC,   SINGULAR, BOOL,     center_zeroed,    12)
#define rocsar_v1_AntennaTelemetry_CALLBACK NULL
#define rocsar_v1_AntennaTelemetry_DEFAULT NULL

extern const pb_msgdesc_t rocsar_v1_AntennaTelemetry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rocsar_v1_AntennaTelemetry_fields &rocsar_v1_AntennaTelemetry_msg

/* Maximum encoded size of messages (where known) */
#define ROCSAR_V1_ROCSAR_V1_COMMON_PB_H_MAX_SIZE rocsar_v1_AntennaTelemetry_size
#define rocsar_v1_AntennaTelemetry_size          81

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
