/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.2 */

#include "pico.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rocsar_v1_SetTargetCommand, rocsar_v1_SetTargetCommand, AUTO)


PB_BIND(rocsar_v1_JogCommand, rocsar_v1_JogCommand, AUTO)


PB_BIND(rocsar_v1_ZeroCommand, rocsar_v1_ZeroCommand, AUTO)


PB_BIND(rocsar_v1_MountCommand, rocsar_v1_MountCommand, AUTO)


PB_BIND(rocsar_v1_DirCommand, rocsar_v1_DirCommand, AUTO)


PB_BIND(rocsar_v1_HeaterCommand, rocsar_v1_HeaterCommand, AUTO)


PB_BIND(rocsar_v1_StopCommand, rocsar_v1_StopCommand, AUTO)


PB_BIND(rocsar_v1_StatusRequestCommand, rocsar_v1_StatusRequestCommand, AUTO)


PB_BIND(rocsar_v1_PicoCommand, rocsar_v1_PicoCommand, AUTO)


PB_BIND(rocsar_v1_PicoAck, rocsar_v1_PicoAck, AUTO)


PB_BIND(rocsar_v1_PicoTelemetry, rocsar_v1_PicoTelemetry, AUTO)


PB_BIND(rocsar_v1_PicoMessage, rocsar_v1_PicoMessage, AUTO)



