/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_ROCSAR_V1_ROCSAR_V1_PICO_PB_H_INCLUDED
#define PB_ROCSAR_V1_ROCSAR_V1_PICO_PB_H_INCLUDED
#include "pb.h"
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rocsar_v1_SetTargetCommand {
    float target_heading_deg;
} rocsar_v1_SetTargetCommand;

/* Absolute tick, valid 0..4095, in manual mode for that axis. */
typedef struct _rocsar_v1_JogCommand {
    uint32_t servo_id;
    uint32_t tick;
} rocsar_v1_JogCommand;

/* Teach a servo its mechanical centre.

 This writes a position offset into the ST3215's own EEPROM (register 0x1F) so
 that the encoder reports 2048 at whatever angle the axis is currently at. The
 firmware verifies both the register read-back and the resulting reported
 position, and refuses with ERROR_CALIBRATION_FAILED if they disagree.

 It relabels the current position; it does NOT drive the axis anywhere. The
 distinction is not pedantic: Waveshare's own tool describes teaching the
 middle and then *commanding* the middle as two separate operations, and only
 the second one moves the servo. So after a successful `zero` the axis has not
 moved, and `current_angle_deg` reads 0 because the position it was already
 in has been redefined as the centre.

 This requires the servo to answer: the offset is computed from a real
 position read, so `zero` on a servo that is not talking is a hardware fault
 rather than a silent no-op. It is a deliberate, comparatively slow operation
 (an EEPROM write, and a read-back to prove it took) and it must not be issued
 automatically on a schedule. */
typedef struct _rocsar_v1_ZeroCommand {
    uint32_t servo_id;
} rocsar_v1_ZeroCommand;

typedef struct _rocsar_v1_MountCommand {
    uint32_t servo_id;
    float offset_deg;
} rocsar_v1_MountCommand;

/* Direction multiplier. Only +1.0 and -1.0 are legal; anything else is a
 parameter error, checked host-side before it reaches the wire. */
typedef struct _rocsar_v1_DirCommand {
    uint32_t servo_id;
    float multiplier;
} rocsar_v1_DirCommand;

typedef struct _rocsar_v1_HeaterCommand {
    uint32_t heater_id;
    bool state;
} rocsar_v1_HeaterCommand;

typedef struct _rocsar_v1_StopCommand {
    uint32_t servo_id;
} rocsar_v1_StopCommand;

typedef struct _rocsar_v1_StatusRequestCommand {
    char dummy_field;
} rocsar_v1_StatusRequestCommand;

typedef struct _rocsar_v1_PicoCommand {
    uint32_t sequence;
    pb_size_t which_payload;
    union {
        rocsar_v1_SetTargetCommand set_target;
        rocsar_v1_JogCommand jog;
        rocsar_v1_ZeroCommand zero;
        rocsar_v1_MountCommand mount;
        rocsar_v1_DirCommand dir;
        rocsar_v1_HeaterCommand heater;
        rocsar_v1_StopCommand stop;
        rocsar_v1_StatusRequestCommand status_request;
    } payload;
} rocsar_v1_PicoCommand;

typedef struct _rocsar_v1_PicoAck {
    uint32_t command_sequence;
    bool success;
    rocsar_v1_ErrorCode error;
} rocsar_v1_PicoAck;

typedef struct _rocsar_v1_PicoTelemetry {
    float gondola_heading_deg;
    float target_heading_deg;
    bool heater1_state;
    bool heater2_state;
    pb_size_t antennas_count;
    rocsar_v1_AntennaTelemetry antennas[2];
    /* Whether gondola_heading_deg is a measurement. False when no BNO055 is
 fitted, in which case the heading is the last bearing *held* rather than a
 reading, and the two are indistinguishable without this bit. A blank proto3
 frame defaults to false, so a frame from a firmware predating this field
 reads as "no measurement", which is the honest reading of one. */
    bool imu_present;
    /* BNO055 die temperature in degrees Celsius, read alongside the heading.
 Only meaningful when imu_present is true: otherwise it is held from the
 last reading (zero at boot), and a blank proto3 frame defaults to zero,
 so it must be read as "no measurement" via imu_present -- the same
 absence discipline as gondola_heading_deg. A field number is the wire;
 do not renumber these fields. */
    float imu_temperature_c;
} rocsar_v1_PicoTelemetry;

typedef struct _rocsar_v1_PicoMessage {
    uint32_t sequence;
    uint64_t timestamp_us;
    pb_size_t which_payload;
    union {
        rocsar_v1_PicoAck ack;
        rocsar_v1_PicoTelemetry telemetry;
    } payload;
} rocsar_v1_PicoMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rocsar_v1_SetTargetCommand_init_default  {0}
#define rocsar_v1_JogCommand_init_default        {0, 0}
#define rocsar_v1_ZeroCommand_init_default       {0}
#define rocsar_v1_MountCommand_init_default      {0, 0}
#define rocsar_v1_DirCommand_init_default        {0, 0}
#define rocsar_v1_HeaterCommand_init_default     {0, 0}
#define rocsar_v1_StopCommand_init_default       {0}
#define rocsar_v1_StatusRequestCommand_init_default {0}
#define rocsar_v1_PicoCommand_init_default       {0, 0, {rocsar_v1_SetTargetCommand_init_default}}
#define rocsar_v1_PicoAck_init_default           {0, 0, _rocsar_v1_ErrorCode_MIN}
#define rocsar_v1_PicoTelemetry_init_default     {0, 0, 0, 0, 0, {rocsar_v1_AntennaTelemetry_init_default, rocsar_v1_AntennaTelemetry_init_default}, 0, 0}
#define rocsar_v1_PicoMessage_init_default       {0, 0, 0, {rocsar_v1_PicoAck_init_default}}
#define rocsar_v1_SetTargetCommand_init_zero     {0}
#define rocsar_v1_JogCommand_init_zero           {0, 0}
#define rocsar_v1_ZeroCommand_init_zero          {0}
#define rocsar_v1_MountCommand_init_zero         {0, 0}
#define rocsar_v1_DirCommand_init_zero           {0, 0}
#define rocsar_v1_HeaterCommand_init_zero        {0, 0}
#define rocsar_v1_StopCommand_init_zero          {0}
#define rocsar_v1_StatusRequestCommand_init_zero {0}
#define rocsar_v1_PicoCommand_init_zero          {0, 0, {rocsar_v1_SetTargetCommand_init_zero}}
#define rocsar_v1_PicoAck_init_zero              {0, 0, _rocsar_v1_ErrorCode_MIN}
#define rocsar_v1_PicoTelemetry_init_zero        {0, 0, 0, 0, 0, {rocsar_v1_AntennaTelemetry_init_zero, rocsar_v1_AntennaTelemetry_init_zero}, 0, 0}
#define rocsar_v1_PicoMessage_init_zero          {0, 0, 0, {rocsar_v1_PicoAck_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define rocsar_v1_SetTargetCommand_target_heading_deg_tag 1
#define rocsar_v1_JogCommand_servo_id_tag        1
#define rocsar_v1_JogCommand_tick_tag            2
#define rocsar_v1_ZeroCommand_servo_id_tag       1
#define rocsar_v1_MountCommand_servo_id_tag      1
#define rocsar_v1_MountCommand_offset_deg_tag    2
#define rocsar_v1_DirCommand_servo_id_tag        1
#define rocsar_v1_DirCommand_multiplier_tag      2
#define rocsar_v1_HeaterCommand_heater_id_tag    1
#define rocsar_v1_HeaterCommand_state_tag        2
#define rocsar_v1_StopCommand_servo_id_tag       1
#define rocsar_v1_PicoCommand_sequence_tag       1
#define rocsar_v1_PicoCommand_set_target_tag     2
#define rocsar_v1_PicoCommand_jog_tag            3
#define rocsar_v1_PicoCommand_zero_tag           4
#define rocsar_v1_PicoCommand_mount_tag          5
#define rocsar_v1_PicoCommand_dir_tag            6
#define rocsar_v1_PicoCommand_heater_tag         7
#define rocsar_v1_PicoCommand_stop_tag           8
#define rocsar_v1_PicoCommand_status_request_tag 9
#define rocsar_v1_PicoAck_command_sequence_tag   1
#define rocsar_v1_PicoAck_success_tag            2
#define rocsar_v1_PicoAck_error_tag              3
#define rocsar_v1_PicoTelemetry_gondola_heading_deg_tag 1
#define rocsar_v1_PicoTelemetry_target_heading_deg_tag 2
#define rocsar_v1_PicoTelemetry_heater1_state_tag 3
#define rocsar_v1_PicoTelemetry_heater2_state_tag 4
#define rocsar_v1_PicoTelemetry_antennas_tag     5
#define rocsar_v1_PicoTelemetry_imu_present_tag  6
#define rocsar_v1_PicoTelemetry_imu_temperature_c_tag 7
#define rocsar_v1_PicoMessage_sequence_tag       1
#define rocsar_v1_PicoMessage_timestamp_us_tag   2
#define rocsar_v1_PicoMessage_ack_tag            3
#define rocsar_v1_PicoMessage_telemetry_tag      4

/* Struct field encoding specification for nanopb */
#define rocsar_v1_SetTargetCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    target_heading_deg,   1)
#define rocsar_v1_SetTargetCommand_CALLBACK NULL
#define rocsar_v1_SetTargetCommand_DEFAULT NULL

#define rocsar_v1_JogCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   tick,              2)
#define rocsar_v1_JogCommand_CALLBACK NULL
#define rocsar_v1_JogCommand_DEFAULT NULL

#define rocsar_v1_ZeroCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1)
#define rocsar_v1_ZeroCommand_CALLBACK NULL
#define rocsar_v1_ZeroCommand_DEFAULT NULL

#define rocsar_v1_MountCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    offset_deg,        2)
#define rocsar_v1_MountCommand_CALLBACK NULL
#define rocsar_v1_MountCommand_DEFAULT NULL

#define rocsar_v1_DirCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    multiplier,        2)
#define rocsar_v1_DirCommand_CALLBACK NULL
#define rocsar_v1_DirCommand_DEFAULT NULL

#define rocsar_v1_HeaterCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   heater_id,         1) \
X(a, STATIC,   SINGULAR, BOOL,     state,             2)
#define rocsar_v1_HeaterCommand_CALLBACK NULL
#define rocsar_v1_HeaterCommand_DEFAULT NULL

#define rocsar_v1_StopCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1)
#define rocsar_v1_StopCommand_CALLBACK NULL
#define rocsar_v1_StopCommand_DEFAULT NULL

#define rocsar_v1_StatusRequestCommand_FIELDLIST(X, a) \

#define rocsar_v1_StatusRequestCommand_CALLBACK NULL
#define rocsar_v1_StatusRequestCommand_DEFAULT NULL

#define rocsar_v1_PicoCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_target,payload.set_target),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,jog,payload.jog),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,zero,payload.zero),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mount,payload.mount),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,dir,payload.dir),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heater,payload.heater),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stop,payload.stop),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status_request,payload.status_request),   9)
#define rocsar_v1_PicoCommand_CALLBACK NULL
#define rocsar_v1_PicoCommand_DEFAULT NULL
#define rocsar_v1_PicoCommand_payload_set_target_MSGTYPE rocsar_v1_SetTargetCommand
#define rocsar_v1_PicoCommand_payload_jog_MSGTYPE rocsar_v1_JogCommand
#define rocsar_v1_PicoCommand_payload_zero_MSGTYPE rocsar_v1_ZeroCommand
#define rocsar_v1_PicoCommand_payload_mount_MSGTYPE rocsar_v1_MountCommand
#define rocsar_v1_PicoCommand_payload_dir_MSGTYPE rocsar_v1_DirCommand
#define rocsar_v1_PicoCommand_payload_heater_MSGTYPE rocsar_v1_HeaterCommand
#define rocsar_v1_PicoCommand_payload_stop_MSGTYPE rocsar_v1_StopCommand
#define rocsar_v1_PicoCommand_payload_status_request_MSGTYPE rocsar_v1_StatusRequestCommand

#define rocsar_v1_PicoAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   command_sequence,   1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, UENUM,    error,             3)
#define rocsar_v1_PicoAck_CALLBACK NULL
#define rocsar_v1_PicoAck_DEFAULT NULL

#define rocsar_v1_PicoTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    gondola_heading_deg,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    target_heading_deg,   2) \
X(a, STATIC,   SINGULAR, BOOL,     heater1_state,     3) \
X(a, STATIC,   SINGULAR, BOOL,     heater2_state,     4) \
X(a, STATIC,   REPEATED, MESSAGE,  antennas,          5) \
X(a, STATIC,   SINGULAR, BOOL,     imu_present,       6) \
X(a, STATIC,   SINGULAR, FLOAT,    imu_temperature_c,   7)
#define rocsar_v1_PicoTelemetry_CALLBACK NULL
#define rocsar_v1_PicoTelemetry_DEFAULT NULL
#define rocsar_v1_PicoTelemetry_antennas_MSGTYPE rocsar_v1_AntennaTelemetry

#define rocsar_v1_PicoMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry,payload.telemetry),   4)
#define rocsar_v1_PicoMessage_CALLBACK NULL
#define rocsar_v1_PicoMessage_DEFAULT NULL
#define rocsar_v1_PicoMessage_payload_ack_MSGTYPE rocsar_v1_PicoAck
#define rocsar_v1_PicoMessage_payload_telemetry_MSGTYPE rocsar_v1_PicoTelemetry

extern const pb_msgdesc_t rocsar_v1_SetTargetCommand_msg;
extern const pb_msgdesc_t rocsar_v1_JogCommand_msg;
extern const pb_msgdesc_t rocsar_v1_ZeroCommand_msg;
extern const pb_msgdesc_t rocsar_v1_MountCommand_msg;
extern const pb_msgdesc_t rocsar_v1_DirCommand_msg;
extern const pb_msgdesc_t rocsar_v1_HeaterCommand_msg;
extern const pb_msgdesc_t rocsar_v1_StopCommand_msg;
extern const pb_msgdesc_t rocsar_v1_StatusRequestCommand_msg;
extern const pb_msgdesc_t rocsar_v1_PicoCommand_msg;
extern const pb_msgdesc_t rocsar_v1_PicoAck_msg;
extern const pb_msgdesc_t rocsar_v1_PicoTelemetry_msg;
extern const pb_msgdesc_t rocsar_v1_PicoMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rocsar_v1_SetTargetCommand_fields &rocsar_v1_SetTargetCommand_msg
#define rocsar_v1_JogCommand_fields &rocsar_v1_JogCommand_msg
#define rocsar_v1_ZeroCommand_fields &rocsar_v1_ZeroCommand_msg
#define rocsar_v1_MountCommand_fields &rocsar_v1_MountCommand_msg
#define rocsar_v1_DirCommand_fields &rocsar_v1_DirCommand_msg
#define rocsar_v1_HeaterCommand_fields &rocsar_v1_HeaterCommand_msg
#define rocsar_v1_StopCommand_fields &rocsar_v1_StopCommand_msg
#define rocsar_v1_StatusRequestCommand_fields &rocsar_v1_StatusRequestCommand_msg
#define rocsar_v1_PicoCommand_fields &rocsar_v1_PicoCommand_msg
#define rocsar_v1_PicoAck_fields &rocsar_v1_PicoAck_msg
#define rocsar_v1_PicoTelemetry_fields &rocsar_v1_PicoTelemetry_msg
#define rocsar_v1_PicoMessage_fields &rocsar_v1_PicoMessage_msg

/* Maximum encoded size of messages (where known) */
#define ROCSAR_V1_ROCSAR_V1_PICO_PB_H_MAX_SIZE   rocsar_v1_PicoMessage_size
#define rocsar_v1_DirCommand_size                11
#define rocsar_v1_HeaterCommand_size             8
#define rocsar_v1_JogCommand_size                12
#define rocsar_v1_MountCommand_size              11
#define rocsar_v1_PicoAck_size                   10
#define rocsar_v1_PicoCommand_size               20
#define rocsar_v1_PicoMessage_size               207
#define rocsar_v1_PicoTelemetry_size             187
#define rocsar_v1_SetTargetCommand_size          5
#define rocsar_v1_StatusRequestCommand_size      0
#define rocsar_v1_StopCommand_size               6
#define rocsar_v1_ZeroCommand_size               6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
