/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_ROCSAR_V1_ROCSAR_V1_PICO_PB_H_INCLUDED
#define PB_ROCSAR_V1_ROCSAR_V1_PICO_PB_H_INCLUDED
#include "pb.h"
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rocsar_v1_SetTargetCommand {
    float target_heading_deg;
} rocsar_v1_SetTargetCommand;

/* Absolute tick, valid 0..4095, in manual mode for that axis. */
typedef struct _rocsar_v1_JogCommand {
    uint32_t servo_id;
    uint32_t tick;
} rocsar_v1_JogCommand;

/* Teach a servo its mechanical centre.

 This writes a position offset into the ST3215's own EEPROM (register 0x1F) so
 that the encoder reports 2048 at whatever angle the axis is currently at. The
 firmware verifies both the register read-back and the resulting reported
 position, and refuses with ERROR_CALIBRATION_FAILED if they disagree.

 It relabels the current position; it does NOT drive the axis anywhere. The
 distinction is not pedantic: Waveshare's own tool describes teaching the
 middle and then *commanding* the middle as two separate operations, and only
 the second one moves the servo. So after a successful `zero` the axis has not
 moved, and `current_angle_deg` reads 0 because the position it was already
 in has been redefined as the centre.

 This requires the servo to answer: the offset is computed from a real
 position read, so `zero` on a servo that is not talking is a hardware fault
 rather than a silent no-op. It is a deliberate, comparatively slow operation
 (an EEPROM write, and a read-back to prove it took) and it must not be issued
 automatically on a schedule. */
typedef struct _rocsar_v1_ZeroCommand {
    uint32_t servo_id;
} rocsar_v1_ZeroCommand;

typedef struct _rocsar_v1_MountCommand {
    uint32_t servo_id;
    float offset_deg;
} rocsar_v1_MountCommand;

/* Direction multiplier. Only +1.0 and -1.0 are legal; anything else is a
 parameter error, checked host-side before it reaches the wire. */
typedef struct _rocsar_v1_DirCommand {
    uint32_t servo_id;
    float multiplier;
} rocsar_v1_DirCommand;

typedef struct _rocsar_v1_HeaterCommand {
    uint32_t heater_id;
    bool state;
} rocsar_v1_HeaterCommand;

typedef struct _rocsar_v1_StopCommand {
    uint32_t servo_id;
} rocsar_v1_StopCommand;

typedef struct _rocsar_v1_StatusRequestCommand {
    char dummy_field;
} rocsar_v1_StatusRequestCommand;

typedef struct _rocsar_v1_PicoCommand {
    uint32_t sequence;
    pb_size_t which_payload;
    union {
        rocsar_v1_SetTargetCommand set_target;
        rocsar_v1_JogCommand jog;
        rocsar_v1_ZeroCommand zero;
        rocsar_v1_MountCommand mount;
        rocsar_v1_DirCommand dir;
        rocsar_v1_HeaterCommand heater;
        rocsar_v1_StopCommand stop;
        rocsar_v1_StatusRequestCommand status_request;
    } payload;
} rocsar_v1_PicoCommand;

typedef struct _rocsar_v1_PicoAck {
    uint32_t command_sequence;
    bool success;
    rocsar_v1_ErrorCode error;
} rocsar_v1_PicoAck;

typedef struct _rocsar_v1_PicoTelemetry {
    float gondola_heading_deg;
    float target_heading_deg;
    bool heater1_state;
    bool heater2_state;
    pb_size_t antennas_count;
    rocsar_v1_AntennaTelemetry antennas[2];
    /* Whether gondola_heading_deg is a measurement. False when no BNO055 is
 fitted, in which case the heading is the last bearing *held* rather than a
 reading, and the two are indistinguishable without this bit. A blank proto3
 frame defaults to false, so a frame from a firmware predating this field
 reads as "no measurement", which is the honest reading of one. */
    bool imu_present;
    /* BNO055 die temperature in degrees Celsius, read alongside the heading.
 Only meaningful when imu_present is true: otherwise it is held from the
 last reading (zero at boot), and a blank proto3 frame defaults to zero,
 so it must be read as "no measurement" via imu_present -- the same
 absence discipline as gondola_heading_deg. A field number is the wire;
 do not renumber these fields. */
    float imu_temperature_c;
    /* Tilt, in degrees. The Euler read returns all three angles and the firmware
 was using only the first.

 The value is as a confidence signal on the heading, not as attitude for its
 own sake. The BNO055 tilt-compensates its fusion *using its accelerometer*,
 and a gondola on a 10-40 m tether swings at roughly 0.08-0.16 Hz -- so sway
 corrupts the tilt estimate that the heading correction depends on. Erratic
 tilt is the tell that the bearing has degraded.

 Held, not zeroed, when the sensor is absent, exactly as the heading is. And
 note that the heading filter passes that pendulum swing through
 unattenuated by design (IMU_ALPHA 0.15 at 50 Hz is a 1.29 Hz cutoff), so a
 bearing that wanders through the swing over a long flight is correct
 behaviour and not a fault. */
    float gondola_roll_deg;
    float gondola_pitch_deg;
    /* The BNO055's calibration status, carried verbatim.

 Register 0x35 (CALIB_STAT) in one byte, two bits per sensor, most
 significant first:

   bits 7-6  system     0=uncalibrated, 3=fully calibrated
   bits 5-4  gyroscope
   bits 3-2  accelerometer
   bits 1-0  magnetometer

 Carried as one uint32 rather than four fields because it is one register and
 four separate fields would cost four tags. A consumer unpacks it; nothing in
 this codebase should need to, since 3 (fully calibrated) in all four is the
 only value that makes a heading trustworthy.

 Why it matters here and not more broadly: a strapospheric flight is 2-24
 hours with a large night-to-day temperature swing at altitude, over which the
 sensor's fusion degrades and wants recalibrating. imu_present says only that
 a sensor answered; this says whether the answer means anything. */
    uint32_t imu_calibration;
    /* The largest linear acceleration seen since boot, per axis, in m/s^2.

 Gravity-free by construction: this is VECTOR_LINEARACCEL, which the sensor
 has already had gravity removed from, so there is no subtraction to get wrong
 and no attitude-dependent error in the peak.

 Monotonic rather than a stream, and that is the design. The events worth
 catching are rare and transient -- balloon rupture into free-fall until the
 chute deploys, the valve transition at the float, recovery shock -- and a
 20 ms sample stream would miss most of them while costing the frame budget
 that attitude and calibration need. A held maximum costs a fixed 18 bytes and
 catches the whole transient. */
    float imu_peak_accel_x_ms2;
    float imu_peak_accel_y_ms2;
    float imu_peak_accel_z_ms2;
    /* Increments once each time imu_peak_accel_* sets a new maximum.

 Once per *sample*, not once per axis: a single shock usually sets all three
 and that is one event, not three. It exists so a consumer can detect "this
 is new" without keeping the history itself -- the peak never decreases, so a
 changed counter means something happened, and an unchanged one means it did
 not, which is all a 1 Hz telemetry link can carry. */
    uint32_t imu_peak_accel_event;
} rocsar_v1_PicoTelemetry;

typedef struct _rocsar_v1_PicoMessage {
    uint32_t sequence;
    uint64_t timestamp_us;
    pb_size_t which_payload;
    union {
        rocsar_v1_PicoAck ack;
        rocsar_v1_PicoTelemetry telemetry;
    } payload;
} rocsar_v1_PicoMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rocsar_v1_SetTargetCommand_init_default  {0}
#define rocsar_v1_JogCommand_init_default        {0, 0}
#define rocsar_v1_ZeroCommand_init_default       {0}
#define rocsar_v1_MountCommand_init_default      {0, 0}
#define rocsar_v1_DirCommand_init_default        {0, 0}
#define rocsar_v1_HeaterCommand_init_default     {0, 0}
#define rocsar_v1_StopCommand_init_default       {0}
#define rocsar_v1_StatusRequestCommand_init_default {0}
#define rocsar_v1_PicoCommand_init_default       {0, 0, {rocsar_v1_SetTargetCommand_init_default}}
#define rocsar_v1_PicoAck_init_default           {0, 0, _rocsar_v1_ErrorCode_MIN}
#define rocsar_v1_PicoTelemetry_init_default     {0, 0, 0, 0, 0, {rocsar_v1_AntennaTelemetry_init_default, rocsar_v1_AntennaTelemetry_init_default}, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rocsar_v1_PicoMessage_init_default       {0, 0, 0, {rocsar_v1_PicoAck_init_default}}
#define rocsar_v1_SetTargetCommand_init_zero     {0}
#define rocsar_v1_JogCommand_init_zero           {0, 0}
#define rocsar_v1_ZeroCommand_init_zero          {0}
#define rocsar_v1_MountCommand_init_zero         {0, 0}
#define rocsar_v1_DirCommand_init_zero           {0, 0}
#define rocsar_v1_HeaterCommand_init_zero        {0, 0}
#define rocsar_v1_StopCommand_init_zero          {0}
#define rocsar_v1_StatusRequestCommand_init_zero {0}
#define rocsar_v1_PicoCommand_init_zero          {0, 0, {rocsar_v1_SetTargetCommand_init_zero}}
#define rocsar_v1_PicoAck_init_zero              {0, 0, _rocsar_v1_ErrorCode_MIN}
#define rocsar_v1_PicoTelemetry_init_zero        {0, 0, 0, 0, 0, {rocsar_v1_AntennaTelemetry_init_zero, rocsar_v1_AntennaTelemetry_init_zero}, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rocsar_v1_PicoMessage_init_zero          {0, 0, 0, {rocsar_v1_PicoAck_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define rocsar_v1_SetTargetCommand_target_heading_deg_tag 1
#define rocsar_v1_JogCommand_servo_id_tag        1
#define rocsar_v1_JogCommand_tick_tag            2
#define rocsar_v1_ZeroCommand_servo_id_tag       1
#define rocsar_v1_MountCommand_servo_id_tag      1
#define rocsar_v1_MountCommand_offset_deg_tag    2
#define rocsar_v1_DirCommand_servo_id_tag        1
#define rocsar_v1_DirCommand_multiplier_tag      2
#define rocsar_v1_HeaterCommand_heater_id_tag    1
#define rocsar_v1_HeaterCommand_state_tag        2
#define rocsar_v1_StopCommand_servo_id_tag       1
#define rocsar_v1_PicoCommand_sequence_tag       1
#define rocsar_v1_PicoCommand_set_target_tag     2
#define rocsar_v1_PicoCommand_jog_tag            3
#define rocsar_v1_PicoCommand_zero_tag           4
#define rocsar_v1_PicoCommand_mount_tag          5
#define rocsar_v1_PicoCommand_dir_tag            6
#define rocsar_v1_PicoCommand_heater_tag         7
#define rocsar_v1_PicoCommand_stop_tag           8
#define rocsar_v1_PicoCommand_status_request_tag 9
#define rocsar_v1_PicoAck_command_sequence_tag   1
#define rocsar_v1_PicoAck_success_tag            2
#define rocsar_v1_PicoAck_error_tag              3
#define rocsar_v1_PicoTelemetry_gondola_heading_deg_tag 1
#define rocsar_v1_PicoTelemetry_target_heading_deg_tag 2
#define rocsar_v1_PicoTelemetry_heater1_state_tag 3
#define rocsar_v1_PicoTelemetry_heater2_state_tag 4
#define rocsar_v1_PicoTelemetry_antennas_tag     5
#define rocsar_v1_PicoTelemetry_imu_present_tag  6
#define rocsar_v1_PicoTelemetry_imu_temperature_c_tag 7
#define rocsar_v1_PicoTelemetry_gondola_roll_deg_tag 8
#define rocsar_v1_PicoTelemetry_gondola_pitch_deg_tag 9
#define rocsar_v1_PicoTelemetry_imu_calibration_tag 10
#define rocsar_v1_PicoTelemetry_imu_peak_accel_x_ms2_tag 11
#define rocsar_v1_PicoTelemetry_imu_peak_accel_y_ms2_tag 12
#define rocsar_v1_PicoTelemetry_imu_peak_accel_z_ms2_tag 13
#define rocsar_v1_PicoTelemetry_imu_peak_accel_event_tag 14
#define rocsar_v1_PicoMessage_sequence_tag       1
#define rocsar_v1_PicoMessage_timestamp_us_tag   2
#define rocsar_v1_PicoMessage_ack_tag            3
#define rocsar_v1_PicoMessage_telemetry_tag      4

/* Struct field encoding specification for nanopb */
#define rocsar_v1_SetTargetCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    target_heading_deg,   1)
#define rocsar_v1_SetTargetCommand_CALLBACK NULL
#define rocsar_v1_SetTargetCommand_DEFAULT NULL

#define rocsar_v1_JogCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   tick,              2)
#define rocsar_v1_JogCommand_CALLBACK NULL
#define rocsar_v1_JogCommand_DEFAULT NULL

#define rocsar_v1_ZeroCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1)
#define rocsar_v1_ZeroCommand_CALLBACK NULL
#define rocsar_v1_ZeroCommand_DEFAULT NULL

#define rocsar_v1_MountCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    offset_deg,        2)
#define rocsar_v1_MountCommand_CALLBACK NULL
#define rocsar_v1_MountCommand_DEFAULT NULL

#define rocsar_v1_DirCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    multiplier,        2)
#define rocsar_v1_DirCommand_CALLBACK NULL
#define rocsar_v1_DirCommand_DEFAULT NULL

#define rocsar_v1_HeaterCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   heater_id,         1) \
X(a, STATIC,   SINGULAR, BOOL,     state,             2)
#define rocsar_v1_HeaterCommand_CALLBACK NULL
#define rocsar_v1_HeaterCommand_DEFAULT NULL

#define rocsar_v1_StopCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_id,          1)
#define rocsar_v1_StopCommand_CALLBACK NULL
#define rocsar_v1_StopCommand_DEFAULT NULL

#define rocsar_v1_StatusRequestCommand_FIELDLIST(X, a) \

#define rocsar_v1_StatusRequestCommand_CALLBACK NULL
#define rocsar_v1_StatusRequestCommand_DEFAULT NULL

#define rocsar_v1_PicoCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_target,payload.set_target),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,jog,payload.jog),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,zero,payload.zero),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mount,payload.mount),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,dir,payload.dir),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heater,payload.heater),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stop,payload.stop),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status_request,payload.status_request),   9)
#define rocsar_v1_PicoCommand_CALLBACK NULL
#define rocsar_v1_PicoCommand_DEFAULT NULL
#define rocsar_v1_PicoCommand_payload_set_target_MSGTYPE rocsar_v1_SetTargetCommand
#define rocsar_v1_PicoCommand_payload_jog_MSGTYPE rocsar_v1_JogCommand
#define rocsar_v1_PicoCommand_payload_zero_MSGTYPE rocsar_v1_ZeroCommand
#define rocsar_v1_PicoCommand_payload_mount_MSGTYPE rocsar_v1_MountCommand
#define rocsar_v1_PicoCommand_payload_dir_MSGTYPE rocsar_v1_DirCommand
#define rocsar_v1_PicoCommand_payload_heater_MSGTYPE rocsar_v1_HeaterCommand
#define rocsar_v1_PicoCommand_payload_stop_MSGTYPE rocsar_v1_StopCommand
#define rocsar_v1_PicoCommand_payload_status_request_MSGTYPE rocsar_v1_StatusRequestCommand

#define rocsar_v1_PicoAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   command_sequence,   1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, UENUM,    error,             3)
#define rocsar_v1_PicoAck_CALLBACK NULL
#define rocsar_v1_PicoAck_DEFAULT NULL

#define rocsar_v1_PicoTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    gondola_heading_deg,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    target_heading_deg,   2) \
X(a, STATIC,   SINGULAR, BOOL,     heater1_state,     3) \
X(a, STATIC,   SINGULAR, BOOL,     heater2_state,     4) \
X(a, STATIC,   REPEATED, MESSAGE,  antennas,          5) \
X(a, STATIC,   SINGULAR, BOOL,     imu_present,       6) \
X(a, STATIC,   SINGULAR, FLOAT,    imu_temperature_c,   7) \
X(a, STATIC,   SINGULAR, FLOAT,    gondola_roll_deg,   8) \
X(a, STATIC,   SINGULAR, FLOAT,    gondola_pitch_deg,   9) \
X(a, STATIC,   SINGULAR, UINT32,   imu_calibration,  10) \
X(a, STATIC,   SINGULAR, FLOAT,    imu_peak_accel_x_ms2,  11) \
X(a, STATIC,   SINGULAR, FLOAT,    imu_peak_accel_y_ms2,  12) \
X(a, STATIC,   SINGULAR, FLOAT,    imu_peak_accel_z_ms2,  13) \
X(a, STATIC,   SINGULAR, UINT32,   imu_peak_accel_event,  14)
#define rocsar_v1_PicoTelemetry_CALLBACK NULL
#define rocsar_v1_PicoTelemetry_DEFAULT NULL
#define rocsar_v1_PicoTelemetry_antennas_MSGTYPE rocsar_v1_AntennaTelemetry

#define rocsar_v1_PicoMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry,payload.telemetry),   4)
#define rocsar_v1_PicoMessage_CALLBACK NULL
#define rocsar_v1_PicoMessage_DEFAULT NULL
#define rocsar_v1_PicoMessage_payload_ack_MSGTYPE rocsar_v1_PicoAck
#define rocsar_v1_PicoMessage_payload_telemetry_MSGTYPE rocsar_v1_PicoTelemetry

extern const pb_msgdesc_t rocsar_v1_SetTargetCommand_msg;
extern const pb_msgdesc_t rocsar_v1_JogCommand_msg;
extern const pb_msgdesc_t rocsar_v1_ZeroCommand_msg;
extern const pb_msgdesc_t rocsar_v1_MountCommand_msg;
extern const pb_msgdesc_t rocsar_v1_DirCommand_msg;
extern const pb_msgdesc_t rocsar_v1_HeaterCommand_msg;
extern const pb_msgdesc_t rocsar_v1_StopCommand_msg;
extern const pb_msgdesc_t rocsar_v1_StatusRequestCommand_msg;
extern const pb_msgdesc_t rocsar_v1_PicoCommand_msg;
extern const pb_msgdesc_t rocsar_v1_PicoAck_msg;
extern const pb_msgdesc_t rocsar_v1_PicoTelemetry_msg;
extern const pb_msgdesc_t rocsar_v1_PicoMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rocsar_v1_SetTargetCommand_fields &rocsar_v1_SetTargetCommand_msg
#define rocsar_v1_JogCommand_fields &rocsar_v1_JogCommand_msg
#define rocsar_v1_ZeroCommand_fields &rocsar_v1_ZeroCommand_msg
#define rocsar_v1_MountCommand_fields &rocsar_v1_MountCommand_msg
#define rocsar_v1_DirCommand_fields &rocsar_v1_DirCommand_msg
#define rocsar_v1_HeaterCommand_fields &rocsar_v1_HeaterCommand_msg
#define rocsar_v1_StopCommand_fields &rocsar_v1_StopCommand_msg
#define rocsar_v1_StatusRequestCommand_fields &rocsar_v1_StatusRequestCommand_msg
#define rocsar_v1_PicoCommand_fields &rocsar_v1_PicoCommand_msg
#define rocsar_v1_PicoAck_fields &rocsar_v1_PicoAck_msg
#define rocsar_v1_PicoTelemetry_fields &rocsar_v1_PicoTelemetry_msg
#define rocsar_v1_PicoMessage_fields &rocsar_v1_PicoMessage_msg

/* Maximum encoded size of messages (where known) */
#define ROCSAR_V1_ROCSAR_V1_PICO_PB_H_MAX_SIZE   rocsar_v1_PicoMessage_size
#define rocsar_v1_DirCommand_size                11
#define rocsar_v1_HeaterCommand_size             8
#define rocsar_v1_JogCommand_size                12
#define rocsar_v1_MountCommand_size              11
#define rocsar_v1_PicoAck_size                   10
#define rocsar_v1_PicoCommand_size               20
#define rocsar_v1_PicoMessage_size               244
#define rocsar_v1_PicoTelemetry_size             224
#define rocsar_v1_SetTargetCommand_size          5
#define rocsar_v1_StatusRequestCommand_size      0
#define rocsar_v1_StopCommand_size               6
#define rocsar_v1_ZeroCommand_size               6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
