# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rocsar/v1/common.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'rocsar/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16rocsar/v1/common.proto\x12\trocsar.v1\"\xbb\x03\n\x10\x41ntennaTelemetry\x12\x19\n\x08servo_id\x18\x01 \x01(\rR\x07servoId\x12\x1f\n\x0bmanual_mode\x18\x02 \x01(\x08R\nmanualMode\x12!\n\x0c\x63urrent_tick\x18\x03 \x01(\rR\x0b\x63urrentTick\x12*\n\x11\x63urrent_angle_deg\x18\x04 \x01(\x02R\x0f\x63urrentAngleDeg\x12\x12\n\x04load\x18\x05 \x01(\x05R\x04load\x12#\n\rtemperature_c\x18\x06 \x01(\x05R\x0ctemperatureC\x12\x1f\n\x0b\x63\x65nter_tick\x18\x07 \x01(\rR\ncenterTick\x12(\n\x10mount_offset_deg\x18\x08 \x01(\x02R\x0emountOffsetDeg\x12%\n\x0e\x64ir_multiplier\x18\t \x01(\x02R\rdirMultiplier\x12%\n\x0e\x66\x65\x65\x64\x62\x61\x63k_state\x18\n \x01(\x05R\rfeedbackState\x12%\n\x0e\x66\x65\x65\x64\x62\x61\x63k_error\x18\x0b \x01(\x05R\rfeedbackError\x12#\n\rcenter_zeroed\x18\x0c \x01(\x08R\x0c\x63\x65nterZeroed*\x88\x02\n\tErrorCode\x12\x0e\n\nERROR_NONE\x10\x00\x12\x19\n\x15\x45RROR_INVALID_COMMAND\x10\x01\x12\x1b\n\x17\x45RROR_INVALID_PARAMETER\x10\x02\x12\x17\n\x13\x45RROR_INVALID_SERVO\x10\x03\x12\x18\n\x14\x45RROR_INVALID_HEATER\x10\x04\x12\x17\n\x13\x45RROR_NOT_CONNECTED\x10\x05\x12\x15\n\x11\x45RROR_UNSUPPORTED\x10\x06\x12\x18\n\x14\x45RROR_HARDWARE_FAULT\x10\x07\x12\x12\n\x0e\x45RROR_INTERNAL\x10\x08\x12\x1c\n\x18\x45RROR_CALIBRATION_FAILED\x10\t\"\x04\x08\n\x10\r*O\n\rFeedbackState\x12\x14\n\x10\x46\x45\x45\x44\x42\x41\x43K_UNKNOWN\x10\x00\x12\x15\n\x11\x46\x45\x45\x44\x42\x41\x43K_MEASURED\x10\x01\x12\x11\n\rFEEDBACK_HELD\x10\x02*\x85\x01\n\x0eSubsystemState\x12\x19\n\x15SUBSYSTEM_UNSPECIFIED\x10\x00\x12\x1a\n\x16SUBSYSTEM_DISCONNECTED\x10\x01\x12\x13\n\x0fSUBSYSTEM_READY\x10\x02\x12\x12\n\x0eSUBSYSTEM_BUSY\x10\x03\x12\x13\n\x0fSUBSYSTEM_ERROR\x10\x04\x42.Z,github.com/rocsar/obc/api/rocsar/v1;rocsarv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rocsar.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/rocsar/obc/api/rocsar/v1;rocsarv1'
  _globals['_ERRORCODE']._serialized_start=484
  _globals['_ERRORCODE']._serialized_end=748
  _globals['_FEEDBACKSTATE']._serialized_start=750
  _globals['_FEEDBACKSTATE']._serialized_end=829
  _globals['_SUBSYSTEMSTATE']._serialized_start=832
  _globals['_SUBSYSTEMSTATE']._serialized_end=965
  _globals['_ANTENNATELEMETRY']._serialized_start=38
  _globals['_ANTENNATELEMETRY']._serialized_end=481
# @@protoc_insertion_point(module_scope)
